# Generated by Django 3.0 on 2021-12-11 04:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comentario',
            old_name='Post',
            new_name='post',
        ),
    ]
