# Generated by Django 3.0 on 2021-12-13 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_post_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='video',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
