# Generated by Django 3.0 on 2021-12-13 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0011_post_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='usuario',
        ),
    ]
