# Generated by Django 3.0 on 2021-12-17 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0025_remove_post_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='descripcion',
            field=models.TextField(max_length=9000),
        ),
        migrations.AlterField(
            model_name='post',
            name='titulo',
            field=models.CharField(max_length=150),
        ),
    ]
