# Generated by Django 3.0 on 2021-12-13 22:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0018_auto_20211213_1836'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='usuario',
        ),
    ]
