# Generated by Django 3.0 on 2021-12-15 18:41

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0021_comentario_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentario',
            name='descripcion',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
